### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by AngeSama** [Bhoonn/bh_accessories#1]
Hello I would like to inform you that I would like to use your mod BH Accessories, but I have 8 Lua errors when I go to the NPC to configure the accessories but it is impossible because of these errors:

**Client-side console error:**

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311: attempt to get length of local 'csms' (a nil value)
    1. DrawEquipped - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311
        2. fn - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:365
            3. unknown - lua/ulib/shared/hook.lua:109

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799: attempt to get length of upvalue 'equipped' (a nil value)
    1. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:269: attempt to index upvalue 'equipped_lookup' (a nil value)
    1. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:269

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:204: bad argument #1 to 'ipairs' (table expected, got nil)
    1. ipairs - [C]:-1
        2. ClearPlayerAdjustments - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:204
            3. HoverOnItem - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:285
                4. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:292

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:204: bad argument #1 to 'ipairs' (table expected, got nil)
    1. ipairs - [C]:-1
        2. ClearPlayerAdjustments - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:204
            3. ExitHoverOnItem - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:304
                4. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:298

**Server side console error:**

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/sh_bh_acc.lua:250: attempt to get length of local 'edd' (a nil value)
  1. WriteEditorData - addons/bh_accessories-main/lua/bh_accessories/sh_bh_acc.lua:250
   2. func - addons/bh_accessories-main/lua/bh_accessories/sv_bh_acc.lua:93
    3. unknown - addons/eprotect_1.3.10/lua/e_protect/server/sv_overrides.lua:21

[Ange Sama|2|STEAM_0:1:20744799] Lua Error:

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311: attempt to get length of local 'csms' (a nil value)
  1. DrawEquipped - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311
   2. fn - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:365
    3. unknown - lua/ulib/shared/hook.lua:109

[Ange Sama|2|STEAM_0:1:20744799] Lua Error:

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799: attempt to get length of upvalue 'equipped' (a nil value)
  1. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799

[Ange Sama|2|STEAM_0:1:20744799] Lua Error:

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311: attempt to get length of local 'csms' (a nil value)
  1. DrawEquipped - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:311
   2. fn - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_draw.lua:365
    3. unknown - lua/ulib/shared/hook.lua:109

[Ange Sama|2|STEAM_0:1:20744799] Lua Error:

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799: attempt to get length of upvalue 'equipped' (a nil value)
  1. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:799

[Ange Sama|2|STEAM_0:1:20744799] Lua Error:

[bh_accessories-main] addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:269: attempt to index upvalue 'equipped_lookup' (a nil value)
  1. unknown - addons/bh_accessories-main/lua/bh_accessories/cl_bh_acc_ui.lua:269
  
  Waiting for your answer
![20210801162902_1](https://user-images.githubusercontent.com/83788874/127774608-14db9f8b-b65b-4014-99e7-078851728f0c.jpg)

**Comment by Bhoonn** [comment]
Those are some weird errors, does your mysqloo connect successfully?

**Comment by AngeSama** [comment]
If mysql is connected correctly it will solve the problem?

**Comment by Bhoonn** [comment]
Yes it will fix all of your problems
